/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   ArcOverlayBackdrop.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, TemplateResult} from 'lit-element';

export {ArcOverlayBackdrop};

/**
 * `arc-overlay-backdrop` is a backdrop used by `ArcOverlayMixin`. It
 * should be a singleton.
 *
 * Originally designed by the Polymer team, ported to LitElement by ARC team.
 *
 * ### Styling
 *
 * The following custom properties and mixins are available for styling.
 *
 * Custom property | Description | Default
 * -------------------------------------------|------------------------|---------
 * `--iron-overlay-backdrop-background-color` | Backdrop background color | #000
 * `--iron-overlay-backdrop-opacity`          | Backdrop opacity | 0.6
 * `--iron-overlay-backdrop`                  | Mixin applied to `iron-overlay-backdrop`.                      | {}
 * `--iron-overlay-backdrop-opened`           | Mixin applied to `iron-overlay-backdrop` when it is displayed | {}
 */
declare class ArcOverlayBackdrop extends LitElement {
  opened: boolean;
  constructor();
  connectedCallback(): void;
  disconnectedCallback(): void;
  render(): TemplateResult;

  /**
   * Appends the backdrop to document body if needed.
   */
  prepare(): void;

  /**
   * Shows the backdrop.
   */
  open(): void;

  /**
   * Hides the backdrop.
   */
  close(): void;

  /**
   * Removes the backdrop from document body if needed.
   */
  complete(): void;
  _onTransitionend(e: CustomEvent): void;

  /**
   * Toggles clas on this element.
   *
   * @param klass CSS class name to toggle
   * @param cond Boolean condition to test whether the class should be
   * added or removwed.
   */
  toggleClass(klass: string, cond: boolean): void;
}
